config/routes.rb
Rails.application.routes.draw do
  resources :screenshots

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: [:show, :edit, :update, :destroy]

  # GET /screenshots
  # GET /screenshots.json
  def index
    @screenshots = Screenshot.all
  end

  # GET /screenshots/1
  # GET /screenshots/1.json
  def show
  end

  # GET /screenshots/new
  def new
    @screenshot = Screenshot.new
  end

  # GET /screenshots/1/edit
  def edit
  end

  # POST /screenshots
  # POST /screenshots.json
  def create
    @screenshot = Screenshot.new(screenshot_params)

    respond_to do |format|
      if @screenshot.save
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully created.' }
        format.json { render :show, status: :created, location: @screenshot }
      else
        format.html { render :new }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenshots/1
  # PATCH/PUT /screenshots/1.json
  def update
    respond_to do |format|
      if @screenshot.update(screenshot_params)
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully updated.' }
        format.json { render :show, status: :ok, location: @screenshot }
      else
        format.html { render :edit }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenshots/1
  # DELETE /screenshots/1.json
  def destroy
    @screenshot.destroy
    respond_to do |format|
      format.html { redirect_to screenshots_url, notice: 'Screenshot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screenshot
      @screenshot = Screenshot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screenshot_params
      params.require(:screenshot).permit(:image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EagleEyeAnalyticsBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/screenshots/_form.html.erb
<%= form_for(@screenshot) do |f| %>
  <% if @screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
      <% @screenshot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenshots/edit.html.erb
<h1>Editing screenshot</h1>

<%= render 'form' %>

<%= link_to 'Show', @screenshot %> |
<%= link_to 'Back', screenshots_path %>

app/views/screenshots/index.html.erb
<h1>Listing screenshots</h1>

<table>
  <thead>
    <tr>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screenshots.each do |screenshot| %>
      <tr>
        <td><%= screenshot.image_url %></td>
        <td><%= link_to 'Show', screenshot %></td>
        <td><%= link_to 'Edit', edit_screenshot_path(screenshot) %></td>
        <td><%= link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screenshot', new_screenshot_path %>

app/views/screenshots/new.html.erb
<h1>New screenshot</h1>

<%= render 'form' %>

<%= link_to 'Back', screenshots_path %>

app/views/screenshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @screenshot.image_url %>
</p>

<%= link_to 'Edit', edit_screenshot_path(@screenshot) %> |
<%= link_to 'Back', screenshots_path %>